"""Add foreign keys to hired_employees

Revision ID: 3a16f3331380
Revises: 92a5a6549067
Create Date: 2024-08-08 11:04:20.521543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a16f3331380'
down_revision: Union[str, None] = '92a5a6549067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'hired_employees', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'hired_employees', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hired_employees', type_='foreignkey')
    op.drop_constraint(None, 'hired_employees', type_='foreignkey')
    # ### end Alembic commands ###
